export const env = {
    FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY,
    FIREBSE_AUTH_DOMAIN: import.meta.env.VITE_FIREBSE_AUTH_DOMAIN,
    FIREBSE_PROJECT_ID: import.meta.env.VITE_FIREBSE_PROJECT_ID,
    FIREBSE_STORAGE_BUCKET: import.meta.env.VITE_FIREBSE_STORAGE_BUCKET,
    FIREBSE_MESSAGING_SENDER_ID: import.meta.env.VITE_FIREBSE_MESSAGING_SENDER_ID,
    FIREBSE_APP_ID: import.meta.env.VITE_FIREBSE_APP_ID,
};
